### ISSUE TITLE
Closing launcher while connecting still leaves the process

### ISSUE THREAD

**Issue by xPaw** [SKCraft/SKMCLauncher#15]
When login server is down, and it takes ages to connect, it leaves the connection thread running even after closing the launcher, and then after a awhile you get popup saying that you couldn't connect, but launcher was closed before that.

**Comment by EntityReborn** [comment]
Another sideeffect of this bug is cancelling a login/update/launch, and not being able to click the launch button again for a while.

**Comment by xPaw** [comment]
This problem still exists. If you cancel connection, it removes the "logging in" window, but then throws the error anyway.

**Comment by sk89q** [comment]
This should be fixed now.
