### ISSUE TITLE
Backup support. (Updating and other situations)

### ISSUE THREAD

**Issue by EntityReborn** [SKCraft/SKMCLauncher#24]
Might be a good idea when updating to backup minecraft.jar, for future reference. 

Thinking for the future, support for multiple backup types (Maps, Bin folder, just minecraft.jar, whole .minecraft folder, etc) would be great, but wouldn't be needed immediately. 
This might be achieved via a "Backup" dialog, with a simple dropdown to select the type, a treeview to select the folder to save to (defaulting to My Documents, or other sane OS-based default), and a text input for the filename, prefilled in with suitable filename.

**Comment by sk89q** [comment]
I'm going to keep profiles entirely within a folder after the coming update, so now backing up can be done by just saving a copy of the entire folder.
