### ISSUE TITLE
Create superdirectories for update-cache.xml

### ISSUE THREAD

**Issue by jwhb** [SKCraft/SKMCLauncher#33]
If the .minecraft folder doesn't exist in the given (e.g. %appdata%) path a FileNotFoundException will be thrown when SKMCL tries to create the file update-cache.xml. A mkdirs() call could be added

**Comment by EntityReborn** [comment]
I thought I fixed this in one of my PRs. Will look into it.

Edit: I did specifically fix this issue, please make sure your launcher is up to date.
