### ISSUE TITLE
Allow normal username in offline mode.

### ISSUE THREAD

**Issue by bardiharborow** [SKCraft/SKMCLauncher#38]
Hi,

Would it be possible to allow the normal username to be used in offline mode (instead of Player).

The default minecraft launcher allows this. I have patchy internet and often play on my home server while the internet is down (temporarily enabling offline mode).

Thanks.

**Comment by md-5** [comment]
Can't due to migrated accounts, unless you want your email as your username.

**Comment by bardiharborow** [comment]
@md_5 What do you mean by "migrated accounts" and why does this prevent it.

**Comment by md-5** [comment]
Because most Minecraft accounts now log in with their email address and not username. The launcher cannot get their username until they have logged in, so if mc.net is down / in offline mode, it can only use their email address.

**Comment by bardiharborow** [comment]
@md_5 Could there be a field in profile configuration for the username to use for offline mode (defaulting to Player). This would allow users to enter a offline username and would mean you don't need to use the email and it keeps the normal "Player" behaviour by default so players aren't surprised by the change. I could organise some code if it's needed.
