### ISSUE TITLE
I do not understand "Digital signature" cutom mods.zip update

### ISSUE THREAD

**Issue by norfair00** [SKCraft/SKMCLauncher#39]
The digital signature how it works

please help my

![Sans titre](https://f.cloud.github.com/assets/1060346/140065/f31b55f4-720f-11e2-9fdd-561089bc21da.png)

excuse me for my bad English I'm French

**Comment by norfair00** [comment]
help me please

**Comment by sk89q** [comment]
Each .zip file has to be "signed" verifying that the person who signed it is a "trusted" person. The launcher ships with "trusted" signatures that are used to figure out whether a signature is trusted.

Unfortunately, besides the fact that I (or Mojang) would have to sign your .zip to make this work, it's a pain for most people if they are not familiar with signing .jars, so I'd like to remove that requirement, but I have not gotten around to it.
