### ISSUE TITLE
Error on launching latest build of the launcher.

### ISSUE THREAD

**Issue by adamjones57** [SKCraft/SKMCLauncher#42]
I'm sorry, I don't know very much about java, but I'll give you this stack trace
http://pastebin.com/Y774StFB

**Comment by brickviking** [comment]
Thanks for that, I'll have to take a look. I'm guessing that you're using this launcher and haven't downloaded minecraft yet? Am I correct?  I managed to duplicate this error by having no .minecraft directory whatsoever.

Regards, brickviking

**Comment by brickviking** [comment]
I've patched, I'll send through a PR to sk89q. Thanks.
