### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by Merlyn42** [SKCraft/SKMCLauncher#44]
I know this is a boring licence question but I was hoping you could clarify your position on the licence for this project.

Currently on https://github.com/sk89q/skmclauncher (2013-03-19) you state that "The launcher is licensed under the GNU General Public License, version 3."

However the LICENCE.txt (which must be considered the "official" source) contains the "GNU LESSER GENERAL PUBLIC LICENSE, Version 3" (note the LESSER), this licence is explicitly used to allow a project to be included in projects which are not licensed under the same (or any) licence. So someone can distribute your code as part of their closed source software.

This is in direct conflict with your statement "Contributions by third parties must be dual licensed under the two licenses described within LICENSE.txt..." 

If you want to ensure your project, which you have generously made free, is only used in similarly licensed software you should change LICENSE.txt to contain GPL3.

Thanks for your work.

**Comment by sk89q** [comment]
The official stance is that one on the front page / in README.md. I must have installed the wrong license file into the repository but did not notice.

Thanks
