### ISSUE TITLE
Storing configs in My Documents\SKMCLauncher? (Windows only)

### ISSUE THREAD

**Issue by sk89q** [SKCraft/SKMCLauncher#48]
I'm thinking of moving the configs to My Documents on Windows.

Originally it was in %APPDATA%, but this folder is not guaranteed to be writable by a non-administrator.

Someone changed it to .minecraft I think. The downside is that it clutters up .minecraft, and also that we may have a problem in the future because the launcher uses some generic filenames ("config.xml" for example).

So I'm thinking about moving over the launcher's data directory to My Documents, which should be writable.

Any objections?

**Comment by bendem** [comment]
Isn't apdata the folder where configs should be ? I tought it was the only folder where application were sure to be able to store information without having admin rights ?

Maybe I missed something...

**Comment by sk89q** [comment]
Nah, you need administrator rights to reliably write into AppData across WIndows versions. If there's an installer, permissions cold be set to make it writable, although that requires administrative permissions to begin with.

**Comment by bendem** [comment]
No objections for me so :+1:

**Comment by ewized** [comment]
How does Minecraft do it then copy what they do.

**Comment by sk89q** [comment]
I think Minecraft has the same problems.

Many of us run as administrators (with UAC) so we don't notice it, but others with limited accounts have the problem I believe. Older versions of Windows (namely Vista) might also be more restrictive.

**Comment by bendem** [comment]
I've just checked and I have full r/w rights with my account without right elevation. So i never run minecraft as administrator.

**Comment by sk89q** [comment]
It's mostly people with "limited accounts" and possibly Vista.

**Comment by ewized** [comment]
I have an idea since the config gets generated on launcher have a check if it can write to appdata and if it received an error ask to save else where.

**Comment by sk89q** [comment]
I thought about that, but that would mean that the configuration could be in several places for any given user and that's be more painful to manage.

That said, I was thinking about switching to "portable mode" rather than let the user choose a destination directory.

But I like the idea of My Documents because it's easy for most people to access.

And I don't like it because it could clutter.

**Comment by ewized** [comment]
I like that idea on portable mode so they can take it to go, yet the My Documents idea is where other games save their data also.

**Comment by bendem** [comment]
I should say, my "documents" folder is a mess... I don't use it at all but all kinds of programs has informations stored there... So everytime i reinstall, i just backup the folder and put it back ^^

**Comment by bardiharborow** [comment]
Currently if you create a file named config.xml in the same directory as the launcher it will use that instead. Why not make that the default. If the user could put SKMCLauncher.jar there in the first place then it should be writable. We could rename it to skmcl_config.xml or something like that if you feel config.xml is too generic.

**Comment by sk89q** [comment]
I notice a bunch of people just put the launcher on their desktop, so it would dump the files all over their desktop.

**Comment by bardiharborow** [comment]
In that case that's ok with me as I use the config.xml method anyway. What the heck was Microsoft thinking restricting APPDATA. Luckily I don't have Vista. Hehehehe. Also, should we make the config.xml in local directory trick easier to find out so that people who object to it being stored in My Documents. I had to root around in the code for half an hour before I worked it out.

**Comment by bardiharborow** [comment]
By the way, can we make the files hidden with java?

**Comment by md-5** [comment]
Only in Java 7, properly anyway.

**Comment by sk89q** [comment]
I also don't think we should be making files hidden.

**Comment by bardiharborow** [comment]
Just a thought.

**Comment by circuitbomb** [comment]
Why not a directory in Program Files/Common Files?

**Comment by jdkula** [comment]
Personally, I was thinking that it would be best to have it in {User Folder}\SKMCLauncher, and same on Linux. On Mac, I was thinking it would be inside the .app, and a button in the GUI to jump to the folder. (.app files are actually folders, and the insides of them are easily accessible with a right-click). And of course, there should be an option to change this in the SKMCLauncher settings.

That's my 2 cents

**Comment by s-zeid** [comment]
> Personally, I was thinking that it would be best to have it in {User Folder}\SKMCLauncher, and same on Linux.

On Linux, if we're going to put the settings folder in the home directory, then it should _definitely_ be a dot-file/hidden.  It would also be possible to use ~/.config/, as many other programs (e.g. Chrome) use that.

> Someone changed it to .minecraft I think. The downside is that it clutters up .minecraft, and also that we may have a problem in the future because the launcher uses some generic filenames ("config.xml" for example).

Maybe use a subfolder of .minecraft—for example, .minecraft/skmclauncher/—or at least a less generic filename?  I would _much_ prefer that as opposed to keeping the SK launcher settings in a separate place.

**Comment by s-zeid** [comment]
Another thought is to add a command-line argument to specify a config path.

**Comment by sk89q** [comment]
I'm rewriting a bulk of the launcher, so I'm probably going to use
- Windows: My Documents\[Folder]
- Mac OS X: wherever it is now/[Folder]
- Linux: $HOME/.folder

And probably add in portable mode switch somehow. Was thinking maybe a portable.txt in the same folder.
