### ISSUE TITLE
1.2.5 update fails: Digital signature of minecraft.jar could not be verified

### ISSUE THREAD

**Issue by xPaw** [SKCraft/SKMCLauncher#5]
The file(s) are signed by an entity that is not registered as 'trusted' with the launcher

**Comment by md-5** [comment]
Did they seriously change the signing certificate. I dont know. Will fix later. Coming back from holiday now.

**Comment by md-5** [comment]
Fixed http://dl.dropbox.com/u/36903976/Jenkins/SKMCLauncher/SKMCLauncher.exe

**Comment by epetousis** [comment]
This is still occurring with me, downloaded 1.2.5.
