### ISSUE TITLE
Allow users to use their own usernames in offline mode

### ISSUE THREAD

**Issue by bardiharborow** [SKCraft/SKMCLauncher#52]
Would it be possible to allow users to use their own usernames in offline mode? Pirating should no longer be a problem with the new "Login once before using offline mode" system. This would allow people to use the same achievement files (at the moment I have to have a symbolic link between them) with online and offline mode and be able to connect to lan servers while offline. I believe this was planned in the launcher.allow-offline-mode setting however that seems to have disappeared.

**Comment by sk89q** [comment]
It's possible. The only reason why I didn't at the time was because I would had to write some more code to handle letting users change the username.
