### ISSUE TITLE
MC 1.6 Requires New Launcher?

### ISSUE THREAD

**Issue by Puremin0rez** [SKCraft/SKMCLauncher#54]
According to this:
http://mcupdate.tumblr.com/post/53355081580/whats-happening-at-mojang

MC 1.6 will require there brand new launcher - what does this mean for SKMC Launcher? I'm assuming it'll be updated to be compatible?

**Comment by sk89q** [comment]
It will be updated.

**Comment by Puremin0rez** [comment]
@sk89q 

Thanks, figured it would. =)

**Comment by khenriks** [comment]
Any news on the progress of 1.6 support?

**Comment by sk89q** [comment]
I currently don't know. I run a modded server myself, but it's still on MC 1.5 and I haven't really had a time / a pressing need to force my hand yet.

**Comment by bendem** [comment]
and if we ask kindly ? :wink:

**Comment by khenriks** [comment]
I've been looking a lot lately into the way the new launcher works and interacts with the actual minecraft client in order to figure out a workaround for my server setup. I'd be happy to write here what I've found out, if it will help with the launcher development.

**Comment by sk89q** [comment]
I'm currently making good progress on this.

**Comment by Puremin0rez** [comment]
@sk89q 

Awesome to hear, greatly miss your launcher :)

**Comment by FabianN** [comment]
@sk89q 

Awesome! Thanks for your contributions to minecraft.

**Comment by dstensnes** [comment]
@sk89q 

Great work! Looking forward to the new version with 1.6 support.

**Comment by sk89q** [comment]
Right now, the launcher can fully download and launch Minecraft. You can create multiple profiles, but you can't edit them yet. I still need to also add UI for login. There's portable mode support, and so on. It's pretty fast too, and you can launch Minecraft very quickly once the launcher is open. Most "tasks," like profile loading, etc. are built to be run in the background (it was so in the last launcher version, but moreso now), so the launcher should feel overall pretty responsive. In addition, all the messages are now properly localized, so the launcher could be translated into another language.

The launcher is reasonably usable at the moment, sans login, but I still need to add in some option dialogs, an optional self-update mechanism, background updating, and modpack support.

There's also a skin now, but that's still open to change. I posted a screenshot a few weeks ago with a full-window image/webpage, but I've abandoned that for something a bit more functional.

![Launcher](https://f.cloud.github.com/assets/38949/1560028/6e4bb9ae-4ff4-11e3-8c47-64fcb38e9d1e.png)

![Create Profile](https://f.cloud.github.com/assets/38949/1560030/75a32ef8-4ff4-11e3-9646-1a8ebb1c42fd.png)

![Version List](https://f.cloud.github.com/assets/38949/1560031/76fa4d04-4ff4-11e3-8aab-c5d842840b92.png)

It's actually been kind of cool playing around with old versions of Minecraft, and I kind of miss how well old versions of the game performed.

![Messages and Errors](https://f.cloud.github.com/assets/38949/1560047/e811f60e-4ff4-11e3-9ae6-fc34c7b11975.png)

**Comment by Puremin0rez** [comment]
@sk89q 

I have to admit, I quite like the very basic "theme" of the original launcher. It's light and uncluttered and I'm not a huge fan of this new dark theme.

**Comment by Magi1053** [comment]
@sk89q Have you considered using a modern (metro) theme, with plain solid colors and no rounded edges?

**Comment by Brottweiler** [comment]
I like the looks of what you show in the images, but I'd rather have a light theme than a dark.

**Comment by sk89q** [comment]
Would you guys prefer a light theme, or a native (to the system) theme? I was planning to add some theme switching so you can choose the one that you prefer.

**Comment by Magi1053** [comment]
I prefer dark, so theme switching

**Comment by bendem** [comment]
I prefer dark as well :wink:

**Comment by sk89q** [comment]
Ha, guess we'll want two themes.

Progress on login:

![Login](https://f.cloud.github.com/assets/38949/1565863/652156e0-5085-11e3-8fed-12592ee94681.png)

![Launcher](https://f.cloud.github.com/assets/38949/1565857/4797db4e-5085-11e3-842e-4512b4dc7884.png)

**Comment by FabianN** [comment]
Personally, I'm more for a native interface. Let the user dictate the style via OS, and the application to follow suit.

**Comment by Magi1053** [comment]
If you wanted to be really fancy, you could have a whole color customization window, where you can change the bg color, text color, button color, etc

**Comment by sk89q** [comment]
The problem with using a native UI is that once I need to do something that Swing doesn't support (like list renderers that contain more than a line of text), it starts failing to look native. One of the biggest annoyances (for me, personally) on the old launcher was that the profile list's selection was _completely wrong_ on Windows. Selections are not supposed to be one solid blue background: they're themed on recent versions of Windows. The other issue is that people complain and want sort of skin.

Regardless, the launcher can support a native theme, a black theme, and a white theme, as well as everything in between. The only difficulty right now is determining what will go in "This is a placeholder" that will work well on all hues.

**Comment by sk89q** [comment]
Hmm, so another option is to use JavaFX for the main launcher frame, and Swing for everything else. 
- JavaFX supports applying CSS to elements, and would allow embedding WebKit.
- Swing allows for a native look.

Downside is that JavaFX would require Java 7u6+, and I've personally never even used it yet.

**Comment by md-5** [comment]
Javafx also needs oracle jre.

**Comment by HenrySlawniak** [comment]
I think a simple light theme and a dark theme should satisfy _mostly_ everyone.

**Comment by jdkula** [comment]
I personally prefer the dark theme, and I think the idea of being able to change the UI colors to the liking of the user is a good one.

**Comment by DarkArc** [comment]
Also swing looks horrible on KDE... (At least in the current launcher)

**Comment by sk89q** [comment]
Ooh I want to see. Screenshot?

**Comment by DarkArc** [comment]
Unfortunately I can't, my linux desktop is back home (I'm 2 1/2 hours away at college). But it's basically terrible old looking blue/grey gradients, nothing is rounded, it's all just very ugly even to my color blind eyes.

**Comment by Magi1053** [comment]
Sounds like how it normally looks on my comp without any look and feel specified

**Comment by DarkArc** [comment]
If your computer isn't KDE Linux, I doubt it. It's truly appalling, it looks like it's from the 90s...

**Comment by Magi1053** [comment]
Something like this? http://imgur.com/enizcQx
or this? http://imgur.com/1ueAvpV

**Comment by DarkArc** [comment]
Actually ya.

**Comment by Magi1053** [comment]
If you're talking about the top one, which is the first one I posted before I edited it, that is the Metal look&feel, which is bundled in the JDK and probably the default swing theme unless you manually specify it

**Comment by DarkArc** [comment]
The top one, it must not be set in the KDE environment. I know in Gnome it doesn't look bad and it fits well. But, KDE leaves it as the default I guess.

I've never had need to make interfaces in Java... So... I didn't know that was the default...

**Comment by sk89q** [comment]
Whose JRE were you using?

**Comment by Magi1053** [comment]
Oracle

**Comment by sk89q** [comment]
I was asking DarkArc in particular.

**Comment by DarkArc** [comment]
Oracle

**Comment by sk89q** [comment]
Two mockups (not in code) I played with for the main frame:

![mockup1](https://f.cloud.github.com/assets/38949/1570647/ba99467a-50f1-11e3-9abf-30af6ade4bda.jpg)

![mockup2](https://f.cloud.github.com/assets/38949/1570655/d9ad3904-50f1-11e3-96d4-d5f622cd716d.jpg)

**Comment by bendem** [comment]
It's nice interface, I like both of them, with a preference for the first one! Will it be the same image for every profile, will it be random or will we have to set it up ourselves ?
If you need something to fill the gap, you could add some stats. Like version, if in custom folder, the number of saves / server, the size of the folder...

**Comment by dstensnes** [comment]
I think both of them look good, so I will let you choose. I am just curious, will there be any RSS or something similar, where I can place the latest news?

**Comment by Puremin0rez** [comment]
@dstensnes That's a brilliant idea! All of that blank space under the "Launch" button could be MC news by default, but if a modpack specified, could be turned into an RSS feed.

**Comment by dstensnes** [comment]
Thanks :)

Sorry, if i brought more work to this project, but really, i just need a version working with minecraft 1.6. Though it would be nice to have a mod related news section of some kind, but that can come later. Thanks anyway, for doing this project!

**Comment by sk89q** [comment]
The space is actually intended for news, but I'm not sure how it's going to look yet.

It's a webpage, so theoretically you could do anything in that space.

**Comment by bardiharborow** [comment]
@sk89q Can I just say that that is the nicest looking launcher I have seen in a long time (ever)! Where do you people get such nice screenshots (the house pic)? Took me a minute to find the differences in each of the mockups. The bottom one has a more Windows 8 feel, but I prefer the top one. Let me know if I can help. =)

**Comment by DarkArc** [comment]
@bardiharborow He has some really great builders on his server. 

@sk89q Personally, I prefer the top one simply because it feels more professional, and it doesn't particularly stick with any OS. As apposed to the bottom picture which -- as @bardiharborow mentioned -- has a somewhat Windows 8 feel just because of the blurred background.

**Comment by sk89q** [comment]
Oh, the house was something I built with some friends. It was for a quest.

**Comment by bardiharborow** [comment]
So @sk89q, if I download the code now what will I get? ie. are those screenshots code or not (not the mockups the earlier ones)? and are you able to launch minecraft?

**Comment by sk89q** [comment]
You get the the screenshots before the mockups. Every version of MC can be downloaded and launched.

But there's no login yet, so you'd be in offline mode essentially and can't join servers.

Note that the launcher currently doesn't clean up files properly after launch yet, so that's going to (slowly) fill up a profile's data folder over time.

**Comment by sk89q** [comment]
OK, sadly I do not think I will finish this.

MC 1.6 and beyond require a laundry list of changes and I do not have time to maintain a launcher. However, the reason I've been maintaining a launcher (since the MC alpha days) was for my server, especially because we use it to deploy our custom modpacks (notably before modded servers were a thing).

For that reason, I forked back my launcher and made a version for my server (kind of like pre-3.x days), but it is completely suited for loading custom modpacks. It's an awful vanilla launcher, but it's pretty solid for a custom one. A lot portion of the code is rewritten or from the new code in the fourth branch on here.

The launcher is now 3-4 MB (1-3 MB pack200'd) because Jackson JSON, Guava, and several libraries are now bundled. That's of course, still pretty small. It's not skinned like the pictures, but that's only because I didn't want to add the 1-3 MB on top. The skin only takes a few lines of code to enable though.

I plan to post the source code later.

**Comment by DarkArc** [comment]
Why so much data for the skin? I imagine the images should be primarily the same image repeated, which shouldn't take up that much data?

**Comment by sk89q** [comment]
Well, the .jar comes with other skins by default.

**Comment by justjanne** [comment]
> I forked back my launcher and made a version for my server (kind of like pre-3.x days), but it is completely suited for loading custom modpacks.

Could you provide the source for this launcher? I think many were only using your Launcher to distribute their own modpack easily.

**Comment by sk89q** [comment]
You can find that here: https://github.com/skcraft/launcher
