### ISSUE TITLE
No matter what I try it wont update the modpack

### ISSUE THREAD

**Issue by profjb** [SKCraft/SKMCLauncher#57]
Ive made a modpack using your build system, but no matter what I do it always goes wrong, it will download fine first time. But everytime I try to launch again.
The update fails and carrys on launching as usual.

I currently it hosted on bitbucket, basicly github but better. I tryed using ftp but it would never load the minecraft.jar for some reason.

I've put the minecraft.jar in the bin folder, I assumed that was right, there wasnt much documentation on this so I wasnt sure. Please help, thanks :).

**Comment by profjb** [comment]
Ive fixed that, I think but now. 

## SK's Minecraft Launcher, v3.2-SNAPSHOT

Java arguments: [-Xms128M, -Xmx4096M, -Dsun.java2d.noddraw=true, -Dsun.java2d.d3d=false, -Dsun.java2d.opengl=false, -Dsun.java2d.pmoffscreen=false, -XX:MaxPermSize=256M]

## Library path: C:\Program Files\Java\jre7\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;;C:\Program Files\Java\jre7\bin;.

Java version: 1.7.0_25
Java architecture: 64
JVM: Java HotSpot(TM) 64-Bit Server VM version 23.25-b01 (vendor: Oracle Corporation)
HEAP initial: 128 MB
HEAP maximum: 3640 MB
NON-HEAP initial: 23 MB

## NON-HEAP maximum: 304 MB

Base directory: C:\Users\Joe\AppData\Roaming.minecraft\instances\unity-one.net84.net_Unity-one
What Minecraft will use: C:\Users\Joe\AppData\Roaming.minecraft\instances\unity-one.net84.net_Unity-one.minecraft
Addon: C:\Users\Joe\AppData\Roaming.minecraft\instances\unity-one.net84.net_Unity-one.minecraft\addons\minecraft.jar\liteloader_1.5.2.zip
Addon: C:\Users\Joe\AppData\Roaming.minecraft\instances\unity-one.net84.net_Unity-one.minecraft\addons\minecraft.jar\minecraftforge-universal-1.5.2-7.8.1.738.zip
List of classpath entries generated!
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/addons/minecraft.jar/liteloader_1.5.2.zip
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/addons/minecraft.jar/minecraftforge-universal-1.5.2-7.8.1.738.zip
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/bin/lwjgl.jar
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/bin/jinput.jar
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/bin/lwjgl_util.jar
Classpath: file:/C:/Users/Joe/AppData/Roaming/.minecraft/instances/unity-one.net84.net_Unity-one/.minecraft/bin/minecraft.jar
Now launching...
Failed to launch
java.lang.NoClassDefFoundError: avu
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
        at java.lang.Class.getConstructor0(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at com.sk89q.mclauncher.launch.GameLauncher.launch(GameLauncher.java:199)
        at com.sk89q.mclauncher.launch.GameLauncher.main(GameLauncher.java:318)
Caused by: java.lang.ClassNotFoundException: avu
        at com.sk89q.mclauncher.launch.RogueClassLoader.findClass(RogueClassLoader.java:97)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
Process ended with code 0
Minecraft is no longer running! Click 'Close Window' to close this window.
Did you know: In 'Options', under 'Environment', you can disable this window from appearing.

**Comment by profjb** [comment]
It seems to download everything, but the minecraft.jar
:(.

**Comment by profjb** [comment]
Now it wont even load any of the mods/coremods.
Installing the minecraft.jar manually
http://pastebin.com/raw.php?i=xjSHeTt8

**Comment by profjb** [comment]
And another error trying to fix this.
http://pastebin.com/bX7j7q5v

Im very sorry but so far the modpack system, no matter what I try it always fails.

**Comment by sk89q** [comment]
It looks like wherever your hosting it is not serving the files correctly.

Try putting it on a regular web host.

**Comment by profjb** [comment]
Sk89, i seem to have fixed the problem. It acctually runs perfectly well on github, believe it or not.
Im very sorry about this post a little rude to be fair, been working on it for 4 days now. So im sure you can understand my frustration, anyway I completely understand it and want to thank you for such a great launcher. Bravo xD.
