### ISSUE TITLE
style change

### ISSUE THREAD

**Issue by darkvip3r** [SKCraft/SKMCLauncher#58]
Hi there, i was wondering if its possible to change the style or layout of the launcher. i would like to customize it.

**Comment by sk89q** [comment]
You can change insofar as that the code is open source and Java has a skinning system.

But you can't apply CSS to the interface, unless we switched to SWT ;)

**Comment by darkvip3r** [comment]
Could you tell me what program i can use to edit the launcher so i ca change the shape and button location? haha nice :D

**Comment by sk89q** [comment]
Well, technically any editor works because you're just editing code.
