### ISSUE TITLE
Won't start on Mac without LWJGL updating, can't get JAWT interface.  

### ISSUE THREAD

**Issue by tsheinen** [SKCraft/SKMCLauncher#59]
Crash report can be found here:
http://pastebin.com/f2BgCZ04

I have tested with both java 6 & 7.  

I'll see if I can fix it, but I am rather new to java so I may not be able to.  I would assume you could do an OS check and if it is a mac download the newer versions of LWJGL.

**Comment by sk89q** [comment]
Going to switch to the new update system so this is going to be irrelevant for now.
