### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by DelusionalLogic** [SKCraft/SKMCLauncher#6]
"Failed to execute goal org.apache.maven.plugins:maven-jarsigner-plugin"

Ran mvn package from the origin folder (the root of the pull) and this is what i got, together with a build failed message.

**Comment by sk89q** [comment]
You have to set these properties:

```
<signerKeyStore />
<signerPassword />
<signerAlias />
```

With -DsignerKeyStore= etc.

These values refer to the values needed to sign the .jar with the jarsigner program.

**Comment by sk89q** [comment]
``` bash
keytool -keystore c:\path\to\keystore -genkey -alias yourname -keypass yourpass
mvn -DsignerKeyStore=c:\path\to\keystore -DsignerPassword=yourpass -DsignerAlias=yourname clean package
```

**Comment by DelusionalLogic** [comment]
Got it working.

I'll leave this here for future reference to anyone else having this problem
http://wiki.plexinfo.net/index.php?title=How_to_sign_JAR_files
