### ISSUE TITLE
Questions reguarding builder_config.xml

### ISSUE THREAD

**Issue by FabianN** [SKCraft/SKMCLauncher#60]
I got a couple questions about setting up the builder_config.xml for automatic building via a CI server.
1. Can I set files/folders to be ignored? I tried this:

```
    </package>
  </templates>
  <files>
    <exclude>.git*</exclude>
    <exclude>README.md</exclude>
  </files>
</config>
```

But that didn't work.

2: Can I set environment settings? Like memory and JVM arguments?

3: Can I have multi-option selections? Say I want to provide three different config options depending on user's computer performance, and have it handle not just what is in the config/ folder but also any config files that may be in the base minecraft directory (such as the settings for optifine)?

**Comment by sk89q** [comment]
1. Not at the moment.
2. No. However, the launcher does set MaxPermGen to 256MB or so if the user doesn't, so you can load in a ton of classes.
3. You can make any file optional.
