### ISSUE TITLE
Spout repo

### ISSUE THREAD

**Issue by ewized** [SKCraft/SKMCLauncher#62]
The repo.spout.org does not exist so I can't compile my own version are their alternatives to get simplenbt.

**Comment by sk89q** [comment]
I swapped the Spout repo with mine so it _should_ be fixed now.

Right now, if you compile the launcher, you still get the old one if you simply run it, so if you want to "play with" the new stuff, use:

``` java
File baseDir = new File("path/to/put/files");
File profileDir = new File(baseDir, "instance");
File sharedDir = new File(baseDir, "shared");

Environment environment = Environment.getInstance();
Session session = new OfflineSession().call();

Profile profile = new SimpleProfile();
profile.setBaseDir(profileDir);
profile.setSharedDir(sharedDir);

Application app = new Minecraft();
profile.setApplication(app);

Version version = app.getLatestStable();
Instance instance = app.getInstance(version, environment);
instance.getUpdater().call();

LaunchContext context = new LaunchContext(Environment.getInstance(), session);
LaunchedProcess p = instance.launch(context);
p.getProcess().waitFor();
p.close();
```

That will download the latest version of MC to a given directory and run it.

You could loop through `app.getAvailable()` and install every MC version for kicks.
