### ISSUE TITLE
 [Modpacks] Rename downloaded files?

### ISSUE THREAD

**Issue by jdkula** [SKCraft/SKMCLauncher#64]
Hello!

I'm creating a modpack and I'm trying to download the 1.4.7 minecraft.jar file; except that the file being downloaded is "1.4.7.jar". How can I rename 1.4.7.jar to minecraft.jar?

I've already tried

```
<file source="http://s3.amazonaws.com/Minecraft.Download/versions/1.4.7/1.4.7.jar" version="014ab0058d5073782900230e27f3113a" size="5005735" dest="bin/minecraft.jar"></file>
```

Thanks!

**Comment by sk89q** [comment]
I don't believe the old update mechanism supports renaming the destination file, unfortunately. You'd probably have to mod the .jar anyway, so you might not be able to download the .jar directly like that.

**Comment by jdkula** [comment]
Alright. I thought it was illegal, however, to distribute the .jar file like that; that's all I was trying to avoid. Okay!

**Comment by sk89q** [comment]
WELL I feel as if it's a prefect legitimate use case in this scenario, plus given that Mojang already hosts all the .jars and lets you download them without login, mirroring a modified version of the .jar isn't providing much additional benefit to someone who doesn't own the game.
