### ISSUE TITLE
Java Proxy Configuration

### ISSUE THREAD

**Issue by pennro-se** [SKCraft/SKMCLauncher#7]
It would be helpful if you added Java Proxy Arguments to the Configuration tab with the rest of it, I would do a Fork but I do not know enough Java to reliably do it myself.

**Comment by sk89q** [comment]
Java proxy arguments?

**Comment by pennro-se** [comment]
Well, if the proxy is an HTML proxy then the arguments are at least part of the following:
"-Dhttp.proxyHost=YourHost -Dhttp.proxyPort=YourPort -Dproxy.User=UserID -Dhttp.proxyPassword=YourPass"
(Always need the proxyHost and proxyPort but the other two don't need to be in there if the proxy doesn't requre it.)
And if you are using a SOCKS proxy then you would use this:
"-DsocksProxyHost=YourHost -DsocksProxyPort=YourPort"

I find that they need to be the most left arguments for them to actually work and I do not know if these will actually work with your set-up as I just assumed that you used a shell command to start minecraft.

**Comment by sk89q** [comment]
Put that in "JVM/Java arguments"

The launcher does not invoke the shell.
